// js/institutions.js — Catálogo de instituciones peruanas para Ariven
window.Institutions = (() => {

  const MALLAS = {
    ing:  ['Álgebra', 'Aritmética', 'Geometría', 'Trigonometría', 'Física', 'Química', 'R. Matemático', 'R. Verbal'],
    bio:  ['Biología', 'Química', 'Física', 'Álgebra', 'Aritmética', 'Geometría', 'Historia del Perú', 'Comprensión Lectora', 'R. Verbal'],
    hum:  ['Historia del Perú', 'Historia Universal', 'Geografía', 'Literatura', 'Filosofía', 'Comprensión Lectora', 'R. Verbal', 'Economía'],
    gen:  ['Álgebra', 'Aritmética', 'Geometría', 'Física', 'Química', 'Historia del Perú', 'Geografía', 'Comprensión Lectora', 'R. Verbal'],
    tec:  ['Matemáticas', 'Física', 'Química', 'R. Matemático', 'R. Verbal', 'Comprensión Lectora'],
    mil:  ['Matemáticas', 'Física', 'Historia del Perú', 'Historia Universal', 'Geografía', 'Comprensión Lectora', 'R. Verbal', 'Cívica'],
    eco:  ['Matemáticas', 'Estadística', 'Economía', 'Comprensión Lectora', 'R. Verbal', 'Historia del Perú', 'Geografía'],
    beca: ['Comprensión Lectora', 'R. Verbal', 'R. Matemático', 'Pensamiento Crítico', 'Hábitos de Estudio']
  };

  const CATS = {
    'univ-pub':  { label: 'Universidad Pública',   icon: '🎓', badge: 'Pública',   cls: 'pub'   },
    'univ-priv': { label: 'Universidad Privada',    icon: '🎓', badge: 'Privada',   cls: 'priv'  },
    'instituto': { label: 'Instituto / Escuela',    icon: '🏫', badge: 'Instituto', cls: 'inst'  },
    'pnp':       { label: 'Policía Nacional',       icon: '👮', badge: 'PNP',       cls: 'pnp'   },
    'ejercito':  { label: 'Ejército del Perú',      icon: '⚔️', badge: 'Ejército',  cls: 'mil'   },
    'marina':    { label: 'Marina de Guerra',       icon: '⚓', badge: 'Marina',    cls: 'mil'   },
    'fap':       { label: 'Fuerza Aérea',           icon: '✈️', badge: 'FAP',       cls: 'mil'   },
    'beca':      { label: 'Programa de Becas',      icon: '🏆', badge: 'Beca',      cls: 'beca'  },
  };

  const DATA = [
    // ── Universidades Públicas (Lima/Callao) ──
    { id:'UNMSM',      name:'Universidad Nacional Mayor de San Marcos',                              abbr:'UNMSM',      aliases:['San Marcos','Decana de América'],                      cat:'univ-pub',  city:'Lima',              dept:'Lima',           malla:'bio',  programs:['Medicina Humana','Odontología','Farmacia y Bioquímica','Enfermería','Nutrición','Obstetricia','Tecnología Médica','Ingeniería Electrónica','Ingeniería Industrial','Ingeniería de Sistemas e Informática','Ingeniería Civil','Ingeniería Química','Ingeniería Mecánica de Fluidos','Física','Matemáticas','Estadística','Computación Científica','Derecho','Economía','Contabilidad','Administración','Negocios Internacionales','Trabajo Social','Arqueología','Historia','Geografía','Lingüística','Literatura','Arte','Filosofía','Psicología','Educación','Agronomía','Medicina Veterinaria','Zootecnia','Pesquería','Biología','Química','Ciencias de la Comunicación'] },
    { id:'UNI',        name:'Universidad Nacional de Ingeniería',                                    abbr:'UNI',        aliases:['La Nacional'],                                         cat:'univ-pub',  city:'Lima',              dept:'Lima',           malla:'ing',  programs:['Ingeniería Civil','Ingeniería Eléctrica','Ingeniería Electrónica','Ingeniería Mecánica','Ingeniería Industrial','Ingeniería de Sistemas','Ingeniería Química','Ingeniería Ambiental','Ingeniería Sanitaria','Ingeniería de Petróleo','Arquitectura y Urbanismo','Ciencias de la Computación','Física','Matemáticas','Ingeniería Económica y Social','Ingeniería de Materiales','Ingeniería Geológica','Ingeniería Geofísica'] },
    { id:'UNALM',      name:'Universidad Nacional Agraria La Molina',                                abbr:'UNALM',      aliases:['La Molina','La Agraria','Agraria'],                    cat:'univ-pub',  city:'Lima',              dept:'Lima',           malla:'bio',  programs:['Agronomía','Ingeniería Agrícola','Ingeniería Forestal','Ingeniería de Industrias Alimentarias','Ingeniería Ambiental','Medicina Veterinaria','Zootecnia','Biología','Economía y Planificación','Nutrición'] },
    { id:'UNFV',       name:'Universidad Nacional Federico Villarreal',                              abbr:'UNFV',       aliases:['Villarreal','Federico Villarreal'],                    cat:'univ-pub',  city:'Lima',              dept:'Lima',           malla:'gen',  programs:['Medicina Humana','Odontología','Tecnología Médica','Enfermería','Psicología','Ingeniería Civil','Ingeniería Electrónica','Ingeniería Industrial','Ingeniería de Sistemas','Ingeniería Informática','Arquitectura','Derecho','Economía','Contabilidad','Administración','Turismo y Hotelería','Trabajo Social','Educación','Biología','Química','Oceanografía','Geografía'] },
    { id:'UNAC',       name:'Universidad Nacional del Callao',                                       abbr:'UNAC',       aliases:['Callao'],                                              cat:'univ-pub',  city:'Callao',            dept:'Callao',         malla:'ing',  programs:['Ingeniería Mecánica de Fluidos','Ingeniería Industrial','Ingeniería Pesquera','Ingeniería de Sistemas','Ingeniería Ambiental','Ingeniería Química','Administración','Contabilidad','Economía','Ingeniería Eléctrica y Electrónica'] },
    { id:'UNE',        name:'Universidad Nacional de Educación Enrique Guzmán y Valle',              abbr:'UNE',        aliases:['La Cantuta','Cantuta','Guzmán y Valle'],               cat:'univ-pub',  city:'Chosica',           dept:'Lima',           malla:'hum',  programs:['Educación Inicial','Educación Primaria','Educación Secundaria — Matemáticas','Educación Secundaria — Ciencias Naturales','Educación Secundaria — Historia y Geografía','Educación Secundaria — Lengua y Literatura','Educación Secundaria — Ciencias Sociales','Educación Secundaria — Educación Física','Educación Secundaria — Inglés','Psicología','Administración'] },
    // ── Universidades Públicas (Norte) ──
    { id:'UNT',        name:'Universidad Nacional de Trujillo',                                      abbr:'UNT',        aliases:['Trujillo'],                                            cat:'univ-pub',  city:'Trujillo',          dept:'La Libertad',    malla:'gen',  programs:['Medicina Humana','Enfermería','Farmacia y Bioquímica','Obstetricia','Odontología','Ingeniería Civil','Ingeniería Industrial','Ingeniería Informática','Ingeniería Química','Ingeniería Agroindustrial','Ingeniería de Industrias Alimentarias','Educación','Biología','Química y Química Industrial','Estadística','Matemáticas','Física','Derecho y Ciencias Políticas','Economía','Contabilidad y Finanzas','Administración','Trabajo Social','Ciencias de la Comunicación','Historia','Arqueología','Turismo','Sociología'] },
    { id:'UNPRG',      name:'Universidad Nacional Pedro Ruiz Gallo',                                 abbr:'UNPRG',      aliases:['Pedro Ruiz Gallo','Lambayeque'],                       cat:'univ-pub',  city:'Chiclayo',          dept:'Lambayeque',     malla:'gen',  programs:['Medicina Humana','Enfermería','Obstetricia','Odontología','Ingeniería Civil','Ingeniería Mecánica y Eléctrica','Ingeniería de Sistemas','Ingeniería Química','Ingeniería Industrial','Ingeniería Agrícola','Agronomía','Ingeniería Zootecnista','Ingeniería de Industrias Alimentarias','Biología Pesquera','Educación','Derecho y Ciencias Políticas','Economía','Contabilidad','Administración','Arqueología','Medicina Veterinaria'] },
    { id:'UNP',        name:'Universidad Nacional de Piura',                                         abbr:'UNP',        aliases:['Piura'],                                               cat:'univ-pub',  city:'Piura',             dept:'Piura',          malla:'gen',  programs:['Medicina Humana','Enfermería','Odontología','Ingeniería Civil','Ingeniería de Petróleo','Ingeniería de Minas','Ingeniería Industrial','Ingeniería Pesquera','Ingeniería Agroindustrial e Industrias Alimentarias','Ingeniería Química','Administración de Empresas','Economía','Contabilidad y Finanzas','Derecho y Ciencias Políticas','Educación'] },
    { id:'UNAT',       name:'Universidad Nacional de Tumbes',                                        abbr:'UNAT',       aliases:['Tumbes'],                                              cat:'univ-pub',  city:'Tumbes',            dept:'Tumbes',         malla:'gen',  programs:['Ingeniería Forestal y del Medio Ambiente','Ingeniería Pesquera','Ingeniería Agroindustrial','Medicina Humana','Enfermería','Obstetricia','Administración en Turismo','Contabilidad','Administración'] },
    { id:'UNS',        name:'Universidad Nacional del Santa',                                        abbr:'UNS',        aliases:['Del Santa','Santa'],                                   cat:'univ-pub',  city:'Chimbote',          dept:'Áncash',         malla:'gen',  programs:['Ingeniería Civil','Ingeniería Industrial','Ingeniería en Energía','Ingeniería Agroindustrial','Ingeniería de Sistemas e Informática','Enfermería','Biología en Acuicultura','Administración','Contabilidad','Economía','Derecho y Ciencias Políticas'] },
    // ── Universidades Públicas (Centro) ──
    { id:'UNCP',       name:'Universidad Nacional del Centro del Perú',                              abbr:'UNCP',       aliases:['Del Centro','Huancayo'],                               cat:'univ-pub',  city:'Huancayo',          dept:'Junín',          malla:'gen',  programs:['Medicina Humana','Enfermería','Obstetricia','Ingeniería Civil','Ingeniería Industrial','Ingeniería Eléctrica','Ingeniería de Minas','Ingeniería Química','Ingeniería en Industrias Alimentarias','Ingeniería de Sistemas','Agronomía','Zootecnia','Medicina Veterinaria','Economía','Administración de Empresas','Contabilidad','Derecho'] },
    { id:'UNDAC',      name:'Universidad Nacional Daniel Alcides Carrión',                           abbr:'UNDAC',      aliases:['Daniel Carrión','Pasco'],                              cat:'univ-pub',  city:'Cerro de Pasco',    dept:'Pasco',          malla:'gen',  programs:['Ingeniería de Minas','Ingeniería Civil','Ingeniería de Sistemas','Ingeniería Ambiental','Medicina Humana','Enfermería','Obstetricia','Educación','Administración','Contabilidad','Derecho'] },
    { id:'UNHEVAL',    name:'Universidad Nacional Hermilio Valdizán',                                abbr:'UNHEVAL',    aliases:['Hermilio Valdizán','Huánuco'],                         cat:'univ-pub',  city:'Huánuco',           dept:'Huánuco',        malla:'gen',  programs:['Medicina Humana','Enfermería','Obstetricia','Odontología','Psicología','Ingeniería Civil','Ingeniería de Sistemas','Educación','Derecho y Ciencias Políticas','Contabilidad','Administración','Idiomas Extranjeros'] },
    { id:'UNH',        name:'Universidad Nacional de Huancavelica',                                  abbr:'UNH',        aliases:['Huancavelica'],                                        cat:'univ-pub',  city:'Huancavelica',      dept:'Huancavelica',   malla:'gen',  programs:['Educación Inicial','Educación Primaria','Educación Secundaria','Ingeniería Civil','Ingeniería de Minas','Ingeniería Ambiental','Zootecnia','Enfermería'] },
    { id:'UNAJMA',     name:'Universidad Nacional José María Arguedas',                              abbr:'UNAJMA',     aliases:['Arguedas','Andahuaylas'],                              cat:'univ-pub',  city:'Andahuaylas',       dept:'Apurímac',       malla:'gen',  programs:['Ingeniería Agroindustrial','Ingeniería en Industrias Alimentarias','Administración de Empresas','Administración','Ingeniería de Sistemas y Telemática'] },
    // ── Universidades Públicas (Sur) ──
    { id:'UNSA',       name:'Universidad Nacional de San Agustín de Arequipa',                       abbr:'UNSA',       aliases:['San Agustín','Arequipa'],                              cat:'univ-pub',  city:'Arequipa',          dept:'Arequipa',       malla:'gen',  programs:['Medicina Humana','Odontología','Farmacia y Bioquímica','Enfermería','Nutrición','Psicología','Ingeniería Civil','Ingeniería Industrial','Ingeniería de Sistemas','Ingeniería Mecánica','Ingeniería Eléctrica','Ingeniería Química','Arquitectura y Urbanismo','Ingeniería de Minas','Ingeniería Metalúrgica','Geología','Física','Matemáticas','Computación','Historia','Filosofía','Comunicación Social','Trabajo Social','Derecho','Economía','Contabilidad','Administración','Turismo y Hotelería','Arqueología','Literatura','Biología','Química'] },
    { id:'UNSAAC',     name:'Universidad Nacional San Antonio Abad del Cusco',                       abbr:'UNSAAC',     aliases:['San Antonio Abad','Cusco','Cusqueña'],                 cat:'univ-pub',  city:'Cusco',             dept:'Cusco',          malla:'gen',  programs:['Medicina Humana','Odontología','Enfermería','Obstetricia','Ingeniería Civil','Ingeniería Industrial','Ingeniería Informática','Ingeniería de Sistemas','Agronomía','Zootecnia','Medicina Veterinaria','Derecho','Economía','Administración','Contabilidad','Turismo','Historia','Arqueología','Educación','Biología','Física','Química','Matemáticas'] },
    { id:'UNJBG',      name:'Universidad Nacional Jorge Basadre Grohmann',                           abbr:'UNJBG',      aliases:['Jorge Basadre','Tacna'],                               cat:'univ-pub',  city:'Tacna',             dept:'Tacna',          malla:'gen',  programs:['Medicina Humana','Enfermería','Obstetricia','Odontología','Ingeniería Civil','Ingeniería Industrial','Ingeniería de Sistemas','Ingeniería Electrónica','Ingeniería Química','Ingeniería Pesquera','Ingeniería de Minas','Agronomía','Ciencias Agropecuarias','Derecho','Economía','Contabilidad','Administración'] },
    { id:'UNAM',       name:'Universidad Nacional de Moquegua',                                      abbr:'UNAM',       aliases:['Moquegua'],                                            cat:'univ-pub',  city:'Moquegua',          dept:'Moquegua',       malla:'gen',  programs:['Ingeniería Ambiental','Ingeniería de Sistemas','Ingeniería Pesquera','Ingeniería Agroindustrial','Trabajo Social','Administración'] },
    { id:'UNSCH',      name:'Universidad Nacional de San Cristóbal de Huamanga',                     abbr:'UNSCH',      aliases:['Huamanga','Ayacucho'],                                 cat:'univ-pub',  city:'Ayacucho',          dept:'Ayacucho',       malla:'gen',  programs:['Medicina Humana','Enfermería','Obstetricia','Odontología','Ingeniería Civil','Ingeniería de Minas','Ingeniería Química','Ingeniería Agroindustrial','Ingeniería Informática y Sistemas','Agronomía','Medicina Veterinaria','Zootecnia','Educación','Derecho','Economía','Administración','Contabilidad','Historia','Arqueología','Biología'] },
    { id:'UNAMBA',     name:'Universidad Nacional Micaela Bastidas de Apurímac',                     abbr:'UNAMBA',     aliases:['Micaela Bastidas','Apurímac'],                         cat:'univ-pub',  city:'Abancay',           dept:'Apurímac',       malla:'gen',  programs:['Ingeniería Civil','Ingeniería de Minas','Ingeniería Informática y Sistemas','Ingeniería Agroindustrial','Administración de Empresas'] },
    // ── Universidades Públicas (Oriente) ──
    { id:'UNAP',       name:'Universidad Nacional de la Amazonía Peruana',                           abbr:'UNAP',       aliases:['Amazonía','Iquitos'],                                  cat:'univ-pub',  city:'Iquitos',           dept:'Loreto',         malla:'bio',  programs:['Medicina Humana','Enfermería','Obstetricia','Odontología','Ingeniería Civil','Ingeniería de Sistemas','Ingeniería Agronómica','Acuicultura','Ingeniería en Gestión Ambiental','Derecho','Economía','Contabilidad','Administración de Empresas','Educación','Biología'] },
    { id:'UNAMAD',     name:'Universidad Nacional Amazónica de Madre de Dios',                       abbr:'UNAMAD',     aliases:['Madre de Dios'],                                       cat:'univ-pub',  city:'Puerto Maldonado',  dept:'Madre de Dios',  malla:'gen',  programs:['Ingeniería Forestal','Ingeniería Ambiental','Administración de Negocios y Turismo','Contabilidad'] },
    // ── Universidades Privadas (Lima) ──
    { id:'PUCP',       name:'Pontificia Universidad Católica del Perú',                              abbr:'PUCP',       aliases:['Católica','La Católica','Pontifica'],                  cat:'univ-priv', city:'Lima',              dept:'Lima',           malla:'gen',  programs:['Ingeniería Civil','Ingeniería Informática','Ingeniería Electrónica','Ingeniería Industrial','Ingeniería Mecánica','Ingeniería Mecatrónica','Ingeniería de Telecomunicaciones','Ciencias de la Computación','Física','Química','Matemáticas','Estadística','Derecho','Economía','Contabilidad','Gestión Empresarial','Administración de Empresas','Finanzas','Negocios Internacionales','Historia','Literatura','Lingüística','Filosofía','Arte — Pintura','Arte — Escultura','Arte — Grabado','Diseño Gráfico','Artes Escénicas','Música','Sociología','Ciencias Políticas','Trabajo Social','Psicología','Comunicaciones','Periodismo','Publicidad','Educación'] },
    { id:'ULima',      name:'Universidad de Lima',                                                   abbr:'ULima',      aliases:['Lima','U Lima'],                                       cat:'univ-priv', city:'Lima',              dept:'Lima',           malla:'eco',  programs:['Ingeniería de Sistemas','Ingeniería Industrial','Ingeniería Civil','Ingeniería de Computación y Sistemas','Administración','Economía','Contabilidad','Marketing','Negocios Internacionales','Finanzas','Derecho','Psicología','Ciencias de la Comunicación','Comunicación Audiovisual y Multimedia'] },
    { id:'UP',         name:'Universidad del Pacífico',                                              abbr:'UP',         aliases:['Pacífico','Del Pacífico'],                             cat:'univ-priv', city:'Lima',              dept:'Lima',           malla:'eco',  programs:['Administración de Empresas','Economía','Contabilidad y Finanzas','Marketing','Negocios Internacionales','Finanzas','Gestión Empresarial','Ingeniería Empresarial'] },
    { id:'USMP',       name:'Universidad de San Martín de Porres',                                   abbr:'USMP',       aliases:['San Martín','San Martín de Porres'],                  cat:'univ-priv', city:'Lima',              dept:'Lima',           malla:'gen',  programs:['Medicina Humana','Odontología','Farmacia y Bioquímica','Enfermería','Nutrición','Ingeniería Civil','Ingeniería de Computación y Sistemas','Ingeniería Electrónica','Ingeniería Industrial','Ingeniería de Gestión Empresarial','Derecho','Economía','Contabilidad','Administración','Marketing','Negocios Internacionales','Psicología','Educación','Ciencias de la Comunicación','Arquitectura','Tecnología Médica'] },
    { id:'UPC',        name:'Universidad Peruana de Ciencias Aplicadas',                             abbr:'UPC',        aliases:['Ciencias Aplicadas'],                                  cat:'univ-priv', city:'Lima',              dept:'Lima',           malla:'ing',  programs:['Ingeniería de Sistemas','Ingeniería Civil','Ingeniería Industrial','Ingeniería Electrónica','Ingeniería Mecatrónica','Ingeniería Ambiental','Ingeniería de Software','Ingeniería de Telecomunicaciones','Arquitectura','Administración','Marketing','Contabilidad y Finanzas','Negocios Internacionales','Finanzas y Contabilidad','Derecho','Psicología','Comunicaciones y Periodismo','Diseño Gráfico','Diseño de Interiores','Diseño de Moda','Gastronomía y Gestión de Restaurantes','Medicina Humana','Odontología','Nutrición y Dietética','Arte y Diseño Empresarial'] },
    { id:'UTP',        name:'Universidad Tecnológica del Perú',                                      abbr:'UTP',        aliases:['Tecnológica'],                                         cat:'univ-priv', city:'Lima',              dept:'Lima',           malla:'ing',  programs:['Ingeniería de Sistemas e Informática','Ingeniería Civil','Ingeniería Industrial','Ingeniería Eléctrica','Ingeniería Electrónica','Ingeniería Ambiental','Ingeniería Mecánica','Ingeniería de Minas','Administración de Empresas','Administración y Negocios del Comercio Internacional','Contabilidad','Marketing y Gestión Comercial','Logística y Cadena de Suministros','Emprendimiento y Negocios','Psicología','Educación Inicial','Educación Primaria','Diseño de Interiores','Diseño Gráfico','Gastronomía y Arte Culinario','Medicina Humana','Enfermería','Farmacia y Bioquímica','Tecnología Médica'] },
    { id:'UPCH',       name:'Universidad Peruana Cayetano Heredia',                                  abbr:'UPCH',       aliases:['Cayetano','Cayetano Heredia'],                         cat:'univ-priv', city:'Lima',              dept:'Lima',           malla:'bio',  programs:['Medicina Humana','Odontología','Farmacia y Bioquímica','Medicina Veterinaria y Zootecnia','Enfermería','Nutrición y Dietética','Tecnología Médica','Terapia Física y Rehabilitación','Psicología','Ciencias Biológicas','Educación'] },
    { id:'UCSUR',      name:'Universidad Científica del Sur',                                        abbr:'UCSUR',      aliases:['Científica del Sur','Científica'],                     cat:'univ-priv', city:'Lima',              dept:'Lima',           malla:'bio',  programs:['Medicina Humana','Odontología','Farmacia y Bioquímica','Enfermería','Nutrición','Psicología','Tecnología Médica','Terapia Física y Rehabilitación','Medicina Veterinaria y Zootecnia','Ingeniería Ambiental','Ingeniería de Sistemas','Ingeniería Civil','Administración de Negocios','Arquitectura'] },
    { id:'USIL',       name:'Universidad San Ignacio de Loyola',                                     abbr:'USIL',       aliases:['San Ignacio','Loyola'],                                cat:'univ-priv', city:'Lima',              dept:'Lima',           malla:'eco',  programs:['Administración de Empresas','Marketing','Negocios Internacionales','Gastronomía y Arte Culinario','Hotelería y Turismo','Arquitectura','Psicología','Ingeniería Industrial','Ingeniería de Sistemas','Nutrición y Dietética','Comunicaciones'] },
    { id:'ESAN',       name:'Universidad ESAN',                                                      abbr:'ESAN',       aliases:['ESAN'],                                                cat:'univ-priv', city:'Lima',              dept:'Lima',           malla:'eco',  programs:['Administración de Negocios','Economía','Marketing y Gestión Comercial','Finanzas y Contabilidad Ejecutiva','Negocios Internacionales','Ingeniería Industrial y Comercial','Ingeniería de Sistemas de Información'] },
    { id:'UIGV',       name:'Universidad Inca Garcilaso de la Vega',                                 abbr:'UIGV',       aliases:['Inca Garcilaso','Garcilaso'],                          cat:'univ-priv', city:'Lima',              dept:'Lima',           malla:'gen',  programs:['Derecho y Ciencias Políticas','Administración','Contabilidad y Finanzas','Psicología','Educación','Ingeniería de Sistemas e Informática','Turismo y Negocios','Farmacia y Bioquímica','Ciencias de la Comunicación','Bromatología y Nutrición','Enfermería','Obstetricia'] },
    { id:'UAP',        name:'Universidad Alas Peruanas',                                             abbr:'UAP',        aliases:['Alas Peruanas','Alas'],                                cat:'univ-priv', city:'Lima',              dept:'Lima',           malla:'gen',  programs:['Derecho','Administración','Contabilidad','Ingeniería Civil','Ingeniería de Sistemas e Informática','Psicología','Educación','Ciencias de la Comunicación','Medicina Humana','Odontología','Enfermería','Obstetricia','Arquitectura','Ingeniería Ambiental'] },
    // ── Universidades Privadas (Regiones) ──
    { id:'UCV',        name:'Universidad César Vallejo',                                             abbr:'UCV',        aliases:['César Vallejo','Vallejo'],                             cat:'univ-priv', city:'Trujillo',          dept:'La Libertad',    malla:'gen',  programs:['Derecho','Administración','Contabilidad','Psicología','Educación Inicial','Educación Primaria','Ingeniería Civil','Ingeniería de Sistemas','Arquitectura','Medicina Humana','Obstetricia','Enfermería','Ciencias de la Comunicación','Marketing y Dirección de Empresas'] },
    { id:'UPAO',       name:'Universidad Privada Antenor Orrego',                                    abbr:'UPAO',       aliases:['Antenor Orrego','Orrego'],                             cat:'univ-priv', city:'Trujillo',          dept:'La Libertad',    malla:'gen',  programs:['Ingeniería Civil','Ingeniería Electrónica','Ingeniería Industrial','Ingeniería de Sistemas','Ingeniería de Software','Arquitectura y Urbanismo','Medicina Humana','Odontología','Estomatología','Enfermería','Psicología','Derecho','Administración','Contabilidad','Economía','Ciencias de la Comunicación','Educación Inicial','Educación Primaria'] },
    { id:'USS',        name:'Universidad Señor de Sipán',                                            abbr:'USS',        aliases:['Señor de Sipán','Sipán'],                              cat:'univ-priv', city:'Chiclayo',          dept:'Lambayeque',     malla:'gen',  programs:['Derecho','Administración','Contabilidad','Ingeniería Civil','Ingeniería de Sistemas','Arquitectura','Psicología','Medicina Humana','Enfermería','Obstetricia','Educación'] },
    { id:'USAT',       name:'Universidad Católica Santo Toribio de Mogrovejo',                       abbr:'USAT',       aliases:['Santo Toribio','Mogrovejo'],                           cat:'univ-priv', city:'Chiclayo',          dept:'Lambayeque',     malla:'gen',  programs:['Ingeniería Civil','Ingeniería de Sistemas y Computación','Ingeniería Industrial','Ingeniería Ambiental','Medicina Humana','Enfermería','Odontología','Administración de Empresas','Contabilidad','Economía','Derecho','Psicología','Educación','Comunicación'] },
    { id:'Continental',name:'Universidad Continental',                                               abbr:'Continental',aliases:['Continental','Huancayo priv'],                         cat:'univ-priv', city:'Huancayo',          dept:'Junín',          malla:'gen',  programs:['Ingeniería Civil','Ingeniería Industrial','Ingeniería Ambiental','Ingeniería de Sistemas e Informática','Ingeniería Mecánica','Ingeniería Eléctrica','Administración','Contabilidad','Derecho','Psicología','Educación','Arquitectura'] },
    { id:'UCSM',       name:'Universidad Católica de Santa María',                                   abbr:'UCSM',       aliases:['Santa María','Católica Arequipa'],                     cat:'univ-priv', city:'Arequipa',          dept:'Arequipa',       malla:'gen',  programs:['Medicina Humana','Odontología','Farmacia y Bioquímica','Enfermería','Obstetricia','Nutrición','Psicología','Ingeniería Civil','Ingeniería Industrial','Ingeniería de Sistemas','Ingeniería Mecánica','Arquitectura y Urbanismo','Derecho','Administración de Empresas','Contabilidad','Economía','Comunicación Social','Educación','Turismo y Hotelería'] },
    { id:'UCSP',       name:'Universidad Católica San Pablo',                                        abbr:'UCSP',       aliases:['San Pablo','Católica San Pablo'],                      cat:'univ-priv', city:'Arequipa',          dept:'Arequipa',       malla:'gen',  programs:['Ingeniería Civil','Ingeniería de Sistemas','Ingeniería Industrial','Administración de Negocios','Contabilidad','Derecho','Psicología','Comunicación'] },
    { id:'ULADECH',    name:'Universidad Católica Los Ángeles de Chimbote',                          abbr:'ULADECH',    aliases:['Los Ángeles','Chimbote priv'],                         cat:'univ-priv', city:'Chimbote',          dept:'Áncash',         malla:'gen',  programs:['Derecho','Administración','Contabilidad','Ingeniería Civil','Ingeniería de Sistemas','Psicología','Educación','Enfermería','Obstetricia','Farmacia y Bioquímica'] },
    { id:'UJCM',       name:'Universidad José Carlos Mariátegui',                                    abbr:'UJCM',       aliases:['José Carlos Mariátegui','Mariátegui'],                 cat:'univ-priv', city:'Moquegua',          dept:'Moquegua',       malla:'gen',  programs:['Medicina Humana','Enfermería','Obstetricia','Ingeniería Ambiental','Ingeniería de Sistemas','Administración','Contabilidad','Derecho'] },
    // ── Institutos y Escuelas ──
    { id:'SENATI',          name:'Servicio Nacional de Adiestramiento en Trabajo Industrial',         abbr:'SENATI',          aliases:['SENATI'],                                        cat:'instituto', city:'Lima',              dept:'Lima',           malla:'tec',  programs:['Mecánica Automotriz','Mecánica de Producción','Electricidad Industrial','Electrónica Industrial','Mecatrónica Automotriz','Administración Industrial','Diseño e Ingeniería de Moda','Computación e Informática','Seguridad Industrial','Refrigeración y Climatización','Construcción Civil'] },
    { id:'TECSUP',          name:'TECSUP — Instituto Tecnológico',                                   abbr:'TECSUP',          aliases:['Tecsup'],                                        cat:'instituto', city:'Lima',              dept:'Lima',           malla:'tec',  programs:['Ingeniería Electrónica','Ingeniería Industrial de Producción','Ingeniería Mecatrónica','Ingeniería de Sistemas de Información','Mecánica Automotriz','Energías Renovables y Eficiencia Energética','Redes y Comunicaciones','Mantenimiento de Maquinaria Pesada'] },
    { id:'SENCICO',         name:'Servicio Nacional de Capacitación para la Industria de la Construcción', abbr:'SENCICO',  aliases:['Sencico'],                                       cat:'instituto', city:'Lima',              dept:'Lima',           malla:'tec',  programs:['Construcción Civil','Instalaciones Sanitarias','Instalaciones Eléctricas','Topografía','Dibujo Técnico de Construcción','Acabados de Construcción'] },
    { id:'CIBERTEC',        name:'CIBERTEC — Instituto de Educación Superior',                       abbr:'CIBERTEC',        aliases:['Cibertec'],                                      cat:'instituto', city:'Lima',              dept:'Lima',           malla:'tec',  programs:['Computación e Informática','Administración de Redes y Comunicaciones','Desarrollo de Software','Diseño Gráfico Publicitario','Administración de Empresas','Administración y Marketing','Contabilidad','Seguridad de la Información'] },
    { id:'IDAT',            name:'Instituto de Administración y Tecnología',                         abbr:'IDAT',            aliases:['IDAT'],                                          cat:'instituto', city:'Lima',              dept:'Lima',           malla:'tec',  programs:['Computación e Informática','Ingeniería de Software','Diseño Gráfico','Administración de Empresas','Marketing y Publicidad','Gastronomía y Arte Culinario','Administración Hotelera y de Restaurantes'] },
    { id:'ToulouseLautrec', name:'Toulouse Lautrec — Escuela Superior de Arte y Diseño',             abbr:'Toulouse',        aliases:['Toulouse','Lautrec','Arte y Diseño'],            cat:'instituto', city:'Lima',              dept:'Lima',           malla:'tec',  programs:['Diseño Gráfico','Diseño de Modas y Textiles','Marketing','Publicidad','Comunicación Visual','Diseño de Espacios y Ambientes'] },
    { id:'CERTUS',          name:'Instituto CERTUS',                                                 abbr:'CERTUS',          aliases:['Certus'],                                        cat:'instituto', city:'Lima',              dept:'Lima',           malla:'tec',  programs:['Administración y Marketing','Contabilidad','Computación e Informática','Diseño Gráfico','Gastronomía y Arte Culinario','Logística y Transporte','Gestión Hotelera'] },
    { id:'ISIL',            name:'Instituto ISIL',                                                   abbr:'ISIL',            aliases:['ISIL'],                                          cat:'instituto', city:'Lima',              dept:'Lima',           malla:'tec',  programs:['Marketing y Publicidad','Diseño Gráfico','Producción Audiovisual','Cine y Televisión','Comunicaciones Digitales','Marketing Digital'] },
    { id:'IPAE',            name:'IPAE Escuela de Empresarios',                                      abbr:'IPAE',            aliases:['IPAE'],                                          cat:'instituto', city:'Lima',              dept:'Lima',           malla:'eco',  programs:['Administración de Negocios','Marketing y Gestión Comercial','Contabilidad y Finanzas','Logística y Cadena de Suministros','Gestión del Talento Humano'] },
    { id:'Khipu',           name:'Instituto Khipu',                                                  abbr:'Khipu',           aliases:['Khipu'],                                         cat:'instituto', city:'Cusco',             dept:'Cusco',          malla:'tec',  programs:['Computación e Informática','Diseño Gráfico','Administración de Empresas','Contabilidad','Enfermería Técnica'] },
    // ── PNP ──
    { id:'EOPNP',           name:'Escuela de Oficiales de la Policía Nacional del Perú',             abbr:'EO PNP',          aliases:['Policía Nacional','PNP Oficiales','EO PNP'],     cat:'pnp',       city:'Lima',              dept:'Lima',           malla:'mil',  programs:['Ciencias Policiales y Administrativas','Especialidad en Investigación Criminal','Especialidad en Orden Público','Especialidad en Inteligencia Policial','Especialidad en Tránsito','Especialidad en Turismo y Ecología'] },
    { id:'ESUBOFPNP',       name:'Escuela de Suboficiales de la Policía Nacional del Perú',          abbr:'ESUBOFPNP',       aliases:['PNP Suboficiales','Suboficiales PNP'],           cat:'pnp',       city:'Lima',              dept:'Lima',           malla:'mil',  programs:['Ciencias Policiales — Orden Público','Ciencias Policiales — Investigación Criminal','Ciencias Policiales — Criminalística','Ciencias Policiales — Tránsito y Seguridad Vial'] },
    // ── Ejército ──
    { id:'EMCH',            name:'Escuela Militar de Chorrillos',                                    abbr:'EMCH',            aliases:['Chorrillos','Militar Chorrillos','EMCH'],        cat:'ejercito',  city:'Lima',              dept:'Lima',           malla:'mil',  programs:['Ciencias Militares — Infantería','Ciencias Militares — Caballería','Ciencias Militares — Artillería','Ciencias Militares — Ingeniería','Ciencias Militares — Comunicaciones','Ciencias Militares — Intendencia','Administración'] },
    { id:'EESE',            name:'Escuela de Suboficiales del Ejército del Perú',                    abbr:'EESE',            aliases:['Suboficiales Ejército','EESE'],                  cat:'ejercito',  city:'Lima',              dept:'Lima',           malla:'mil',  programs:['Técnico en Ciencias Militares — Infantería','Técnico en Ciencias Militares — Artillería','Técnico en Ciencias Militares — Ingeniería','Técnico en Ciencias Militares — Comunicaciones','Técnico en Administración Militar'] },
    // ── Marina ──
    { id:'ESNA',            name:'Escuela Naval del Perú',                                           abbr:'ESNA',            aliases:['La Naval','Naval','Escuela Naval'],               cat:'marina',    city:'Lima',              dept:'Lima',           malla:'mil',  programs:['Ciencias Navales — Operaciones','Ciencias Navales — Ingeniería Naval','Ciencias Navales — Infantería de Marina','Ciencias Navales — Intendencia','Administración Naval'] },
    { id:'ESMGP',           name:'Escuela de Suboficiales de la Marina de Guerra del Perú',          abbr:'ESMGP',           aliases:['Suboficiales Marina','Marina Suboficiales'],     cat:'marina',    city:'Lima',              dept:'Lima',           malla:'mil',  programs:['Técnico en Operaciones Navales','Técnico en Ingeniería Naval','Técnico en Electrónica Naval','Técnico en Sanidad Naval'] },
    // ── FAP ──
    { id:'EOFAP',           name:'Escuela de Oficiales de la Fuerza Aérea del Perú',                 abbr:'EOFAP',           aliases:['FAP Oficiales','Fuerza Aérea Oficiales'],        cat:'fap',       city:'Lima',              dept:'Lima',           malla:'mil',  programs:['Ciencias Aeronáuticas — Piloto Militar','Ciencias Aeronáuticas — Ingeniería Aeronáutica','Ciencias Aeronáuticas — Administración Aeronáutica','Ciencias Aeronáuticas — Sistemas de Armas'] },
    { id:'ESFAP',           name:'Escuela de Suboficiales de la Fuerza Aérea del Perú',              abbr:'ESFAP',           aliases:['FAP Suboficiales','Fuerza Aérea Suboficiales'],  cat:'fap',       city:'Lima',              dept:'Lima',           malla:'mil',  programs:['Técnico en Mantenimiento de Aeronaves','Técnico en Electrónica Aeronáutica','Técnico en Meteorología','Técnico en Comunicaciones Aeronáuticas','Técnico en Administración Aeronáutica'] },
    // ── Becas ──
    { id:'Beca18',          name:'Beca 18 — PRONABEC',                                               abbr:'Beca 18',         aliases:['Beca 18','PRONABEC','Pronabec'],                 cat:'beca',      city:'(Nacional)',        dept:'',               malla:'beca', programs:['Ingeniería','Medicina y Salud','Educación','Agronomía','Tecnología e Informática','Ciencias Sociales','Derecho','Administración','Ciencias Básicas'] },
  ];

  // Index for O(1) lookup
  const _idx = Object.create(null);
  DATA.forEach(e => { _idx[e.id] = e; });

  function _norm(s) {
    return (s || '').toLowerCase()
      .normalize('NFD').replace(/[̀-ͯ]/g, '')
      .replace(/[^a-z0-9 ]/g, ' ')
      .replace(/  +/g, ' ').trim();
  }

  function _score(entry, q) {
    const nq   = _norm(q);
    const nid  = _norm(entry.id);
    const nabb = _norm(entry.abbr || '');
    const nnam = _norm(entry.name);

    if (nabb && nabb === nq)            return 100;
    if (nid  && nid  === nq)            return 100;
    if (nabb && nabb.startsWith(nq))    return 90;
    if (nid  && nid.startsWith(nq))     return 90;

    for (const a of (entry.aliases || [])) {
      const na = _norm(a);
      if (na === nq)                    return 85;
    }
    if (nnam.startsWith(nq))            return 80;
    for (const a of (entry.aliases || [])) {
      const na = _norm(a);
      if (na.startsWith(nq))            return 70;
    }
    if (nnam.includes(nq))              return 60;
    for (const a of (entry.aliases || [])) {
      const na = _norm(a);
      if (na.includes(nq))              return 50;
    }
    return 0;
  }

  function search(query, limit) {
    limit = limit == null ? 8 : limit;
    if (!query || !query.trim()) return [];
    const scored = [];
    for (let i = 0; i < DATA.length; i++) {
      const s = _score(DATA[i], query);
      if (s > 0) scored.push({ entry: DATA[i], s });
    }
    scored.sort((a, b) => b.s - a.s);
    return scored.slice(0, limit).map(x => x.entry);
  }

  function getById(id) {
    return _idx[id] || null;
  }

  function getMalla(id) {
    const entry = _idx[id];
    if (!entry) return [];
    return MALLAS[entry.malla] || [];
  }

  function getCatMeta(cat) {
    return CATS[cat] || { label: cat, icon: '🎓', badge: cat, cls: '' };
  }

  const _RECENT_KEY = 'arv-inst-recent-v1';
  const _RECENT_MAX = 5;

  function getRecent() {
    try {
      return JSON.parse(localStorage.getItem(_RECENT_KEY) || '[]');
    } catch (e) {
      return [];
    }
  }

  function saveRecent(id) {
    try {
      const list = getRecent().filter(x => x !== id);
      list.unshift(id);
      localStorage.setItem(_RECENT_KEY, JSON.stringify(list.slice(0, _RECENT_MAX)));
    } catch (e) { /* quota exceeded or private mode */ }
  }

  return { search, getById, getMalla, getCatMeta, getRecent, saveRecent };
})();
